### ISSUE TITLE
variation.html?

### ISSUE THREAD

**Issue by cmita** [FunnelEnvy/optimizely-cli#29]
Could we have a file in the experiment directory that is something like variation.html? We have variation.js and variation.css, but variation.html would be very helpful too.

**Comment by axs89** [comment]
Thanks for the comment. I'm having a little trouble understanding what the variation.html would do in this case. Would it be static html that the variation runs against?

**Comment by casevanarkel** [comment]
Pretty much what she is referring to, is a copy of example.html stored locally as example.variation.html, so we can see changes first before pushing every time to optimizely

**Comment by axs89** [comment]
So the intent of the `host` command is exactly that - to be able to see the changes and debug in the local browser before pushing to Optimizely. Were you able to get that working? It's analogous to the way Optimizely works in that it executes the JS / CSS against the page in the browser.

Trying to write HTML to the filesystem that is the result of JS DOM manipulation is (at least for me) a non-trivial technical problem. That's all happening in memory as far as I know, and on top of that there very well could be other JS affecting the page.

Is there a reason you want to look at the file as document as a static file on the filesystem vs the actual result of the variation in the browser? Sorry if I'm being obtuse - maybe our workflow is different or we haven't communicated the use of `host` properly.

**Comment by casevanarkel** [comment]
Okay, we understand. Yes, we were able to get that working.

Another question: 

what's the typical lag time or wait time between when you push the code to CLI and when you see the changed reflected in Optimizely?

**Comment by casevanarkel** [comment]
Makes sense! Yes we got that working. Thank you.

**Comment by axs89** [comment]
@casevanarkel great! To answer your earlier question there shouldn't be any real lag time between the push and the experiment / variation showing up in Optimizely. If you're seeing that repeatedly let us know, especially if there are any ways you can reproduce it.
