### ISSUE TITLE
asset management

### ISSUE THREAD

**Issue by axs89** [FunnelEnvy/optimizely-cli#32]
I'm strongly thinking of replacing the current assets functionality and supporting functionality like templating in a more robust way. An asset pipeline approach comes to mind with something like [Mincer](http://nodeca.github.io/mincer/) but I'd love to hear any other opinions / thoughts / feedback?

**Comment by johnhenryenvy** [comment]
So, looking at what we need, [Enchillada](https://github.com/defunctzombie/node-enchilada) might do at least some of what we need.

**Comment by johnhenryenvy** [comment]
We're doing two things: we're going to add a task flag (--task) to allow optcli to run specific tasks runners (such as broccoli, grunt, and gulp) when running host.
Templating (as well as transpiling, or other transformations) will be the domain of the task runner.
We're also adding a live flag (--live) to automatically reload pages when a hosted directory changes that can be used in conjunction with a taskrunner's 'watch' command.

**Comment by nselvidge** [comment]
Optcli should not be heavily opinionated on how you write tests, so we're going to build in support for a src and dist folder to allow users to more easily build their tests using the taskrunners that they're used to, but without forcing a specific implementation on them.
