### ISSUE TITLE
Optcli host should intelligently place "optcli=activate" within the url before hash ("#")

### ISSUE THREAD

**Issue by johnhenryenvy** [FunnelEnvy/optimizely-cli#41]
Items after the hash aren't processed by the server and thus not recognized by Tampermonkey. We need to sure that optcli test parameters come before it to ensure that they activate the local URL for testing.

Example:
 www.google.com?optcli=activate (Activates)
 www.google.com?#optcli=activate (Doesn't activate)

**Comment by nselvidge** [comment]
fixed in #54
