### ISSUE TITLE
Fix host command tests

### ISSUE THREAD

**Issue by tmaiaroto** [FunnelEnvy/optimizely-cli#59]
Timeout warnings and the ```before()``` seems to have a hiccup somewhere along the way.

**Comment by tmaiaroto** [comment]
The child process being spawned is exiting with a code of 8. I think this happens when the port is in use (I'm currently running ```optcli host``` when running tests) or when you don't have permission to bind to the port (which we likely don't have on the CI service).

**Comment by nselvidge** [comment]
It looks like the issue was probably being caused by running optcli without having installed it first. I don't think it's really necessary to run it through the console so I'm modifying the test to just directly call the host command by require()ing host.js

**Comment by tmaiaroto** [comment]
Also verified with Codeship that we can listen on ports (though that wasn't the case here).

**Comment by nselvidge** [comment]
fixed with #62
