### ISSUE TITLE
optcli host command broken

### ISSUE THREAD

**Issue by plus-x** [FunnelEnvy/optimizely-cli#69]
Hello there,

I ran the commands optcli experiment and variation with no problems. My experiment directory contains:

drwxr-xr-x  4 carlos  staff  136 Sep 14 03:47 Load JS
-rw-r--r--  1 carlos  staff   90 Sep 14 03:45 experiment.json
-rw-r--r--  1 carlos  staff    0 Sep 14 03:45 global.css
-rw-r--r--  1 carlos  staff    0 Sep 14 03:45 global.js

While IN this directory, when I run:

optcli host .

I get "error: no experiment.json found"

I get this error no matter where I run the host command. The experiment.json file is clearly there. No solution, no one else talking about this, no idea what to do :(

Thanks for any help!!

**Comment by nselvidge** [comment]
@plus-x you'll need to use the path to the variation you want to host and not the experiment. Also, you should call it from the project folder not from the experiment folder. 

```
optcli host experiment-folder/variation-folder
```

**Comment by plus-x** [comment]
Ah yes, I just realized this. This is not explicitly stated in the instructions below the video on your page here:

http://www.funnelenvy.com/optimizely-cli/

I was only able to catch that by re-watching the entire video.

I would say please write this into the instructions on that page more clearly, and close the issue?? :-) :+1:
